name: Monitor Website

on:
  schedule:
    # On passe à 5 minutes pour éviter la mise en veille de Render
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render
        run: |
          curl -fL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) GitHubActions/1.0" \
          --connect-timeout 30 \
          --retry 2 \
          https://formations-civique.onrender.com \
          -o /dev/null
